#!/bin/bash

set -e -x -o pipefail

echo $(pwd)

declare -a PROVIDERS=( "provider-aws@v0.44.2" "provider-azure@v0.20.0" "provider-gcp@v0.22.0" )

for p in "${PROVIDERS[@]}"; do
    go get "github.com/crossplane-contrib/${p}"

    find "${GOPATH}/pkg/mod/github.com/crossplane-contrib/${p}/apis" -name "*.go" | xargs -I {} dirname {} | uniq | xargs cue get go
done

declare -a ADDITIONAL_PACKAGES=( "github.com/crossplane/crossplane-runtime/apis/common/v1@v1.14.1" )

for pkg in "${ADDITIONAL_PACKAGES[@]}"; do
    go get "${pkg}"

    cue get go "${pkg}"
done

mv cue.mod out
